import type { Metadata } from "next";
import "./style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main className="max-w-[1080px] min-h-[100vh] mx-auto flex flex-col items-start gap-3 flex-[1_0_0] self-stretch rounded-[10px_0_0_0] bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
